### ISSUE TITLE
more_clear_input_headers 'Variable-*' 'Shib-*'

### ISSUE THREAD

**Issue by kosarko** [nginx-shib/nginx-http-shibboleth#13]
As more_clear_input_headers is still not working with wildcards (https://github.com/openresty/headers-more-nginx-module/issues/15), it might be reasonable to update the example configuration.

Do you know of another way of removing those headers?

**Comment by davidjb** [comment]
Manually is the way to go at present, specify each one. Alternatively, you could write nginx JS (or Lua) to implement the removal. 

For now,  I'll update the docs. Hopefully that project gets that update.  Otherwise PR are welcome with other solutions!

**Comment by davidjb** [comment]
Could you help add support over at the other issue (eg a +1 etc)?

**Comment by davidjb** [comment]
Fixed in development branch; will create a new release in the near future.  Thanks for the issue report!
