### ISSUE TITLE
dynamic module support

### ISSUE THREAD

**Issue by rabb1t** [nginx-shib/nginx-http-shibboleth#14]
Hello,

Starting from nginx-1.9.11 developers added a new feature called [dynamic modules](http://nginx.org/en/docs/ngx_core_module.html#load_module)

Can you please add support for compile this module as a dynamic to enable the possibility to explicitly load the module adding `load_module` directive inside the nginx configuration file , e.g:

`load_module /path/to/modules/ngx_http_shibboleth_module.so;`

Thank you in advance!

**Comment by davidjb** [comment]
Already done from a while ago, check the development branch. I'm using the dynamic module in prod plus it is now Travis tested, but more testing is always needed. 

I'll be making a new release v2 shortly. 

Thanks for the report!

**Comment by davidjb** [comment]
Released v2.0.0, merged into master and tagged @ https://github.com/nginx-shib/nginx-http-shibboleth

**Comment by rabb1t** [comment]
@davidjb Thank you for a quick update!
