### ISSUE TITLE
Question: Install this in AWS Elastic Beanstalk?

### ISSUE THREAD

**Issue by aaron-collier** [nginx-shib/nginx-http-shibboleth#24]
### Description of Issue/Question
The instance/configuration of NGINX on elastic beanstalk seems to make it very difficult to dynamically load modules. 

Does anyone have experience or advice on getting this loaded in an elastic beanstalk environment?

### Setup
Current environment is: 64bit Amazon Linux 2017.03 v2.4.2 running Ruby 2.3 (Puma)

Thanks.

**Comment by dcale** [comment]
hi @aaron-collier I got this working with a docker-compose setup. So maybe instead of elastic beanstalk, amazon's ECS should definitely work.

**Comment by aaron-collier** [comment]
Thanks @dcale - that may be the direction this has to go. Was hoping to stick to straight `eb deploy`-able configurations, but docker may be the best solution, for now...
