### ISSUE TITLE
How to upgrade shibboleth version on nginx?

### ISSUE THREAD

**Issue by RohitVenturit** [nginx-shib/nginx-http-shibboleth#34]
### Description of Issue/Question
(Be as detailed as possible)
**shibd -v** command is showing which is appears to be **shibboleth 2.5.3** 
I want to get it upgraded to v3 
shibboleth site does not give clear steps for upgrading https://wiki.shibboleth.net/confluence/display/SP3/UpgradingFromV2 
so how to upgrade to latest version of Shibboleth SP ?
### Setup
(Please provide relevant configuration files; be sure to remove sensitive
info)

### Steps to Reproduce Issue
(Include debug logs if possible, see
http://nginx.org/en/docs/debugging_log.html; be sure to remove sensitive info)

### Versions and Systems
(`nginx -V`, `shibd -v` (and compile options), OS type and version)
nginx version: nginx/1.15.3
shibd version: hibboleth 2.5.3
ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-1067-aws x86_64)

**Comment by davidjb** [comment]
Concerns about documentation or the core of the Shibboleth SP should be raised with the official Shibboleth community (https://www.shibboleth.net/community/).  Note that this repo is specifically for the unofficial Nginx module that lets Nginx communicate with the FastCGI applications from a  Shibboleth SP instance.  If there are issues with this Nginx communicating with correctly-configured v3 FastCGI applications, then do raise an issue about that.  Thanks.
