### ISSUE TITLE
Problem with ECP

### ISSUE THREAD

**Issue by misterx001** [nginx-shib/nginx-http-shibboleth#35]
I've installed the module and shibboleth 3 SP from the pre-built RPMs, and everything works perfectly with the notable exception of ECP. All I can seem to get is "Status: 500 Server Error" in the nginx debug logs. Shibd's logs show no errors, and the IdP shows nothing.

I'm using a modified python script to attempt to connect and I can't even get past the first request for a protected resource with the PAOS and Accept headers.

Can anyone point me in the right direction?

Any help is appreciated.

**Comment by davidjb** [comment]
ECP isn't something I've had experience with, but for anyone else to assist, posting the relevant bits of your Nginx and Shibboleth configuration would be helpful.  Looking at the ECP docs (https://wiki.shibboleth.net/confluence/display/CONCEPT/ECP#ECP-ImplementingClients) possible culprits could be anything from HTTP headers, cookies, Nginx configuration, to Shib SP configuration or even limited support in the FastCGI apps.  Perhaps try getting the config working with Apache or IIS first and then look at how that translates to Nginx.

For greater access to support, you should definitely post to the Mailing Lists for Shibboleth (https://www.shibboleth.net/community/) and see if anyone can assist.
